# Generated by Django 3.0.3 on 2020-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=120)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=240, null=True)),
                ('feedback', models.TextField(db_column='feedback', max_length=120)),
                ('added_at', models.TimeField(auto_now_add=True, db_column='added_at')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
    ]
