# Generated by Django 3.0.3 on 2020-04-16 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_rating', models.FloatField(blank=True, db_column='price_rating', default=1, null=True)),
                ('source_rating', models.FloatField(blank=True, db_column='source_rating', default=1, null=True)),
                ('speed_rating', models.FloatField(blank=True, db_column='speed_rating', default=1, null=True)),
                ('comment', models.TextField(blank=True, db_column='comment', null=True)),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ratings',
                'db_table': 'Rating',
            },
        ),
    ]
