# Generated by Django 3.0.3 on 2020-04-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0002_rating_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(blank=True, db_column='comment', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on'),
        ),
    ]
