# Generated by Django 3.0.3 on 2020-04-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '__first__'),
        ('Rating', '0003_auto_20200419_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='products.Product'),
        ),
    ]
