# Generated by Django 3.0.3 on 2020-04-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='id',
        ),
        migrations.AlterField(
            model_name='queries',
            name='search',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
