# Generated by Django 3.0.3 on 2020-03-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'CategoryList',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_column='source', max_length=255)),
                ('slug', models.SlugField(db_column='slug', unique=True)),
            ],
            options={
                'db_table': 'Source',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_column='product_name', max_length=256)),
                ('product_price', models.CharField(db_column='product_price', max_length=120)),
                ('product_url', models.CharField(db_column='product_url', max_length=120)),
                ('product_images', models.CharField(blank=True, db_column='product_images', max_length=120, null=True)),
                ('product_category', models.ForeignKey(db_column='product_category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Categories')),
                ('product_source', models.OneToOneField(db_column='product_source', on_delete=django.db.models.deletion.CASCADE, to='products.Source')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
