# Generated by Django 3.0.3 on 2020-03-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='id',
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(db_column='name', max_length=120),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(db_column='slug', primary_key=True, serialize=False, unique=True),
        ),
    ]
