# Generated by Django 3.0.3 on 2020-03-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200308_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(db_column='product_price'),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.SlugField(db_column='slug', primary_key=True, serialize=False),
        ),
    ]
